using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Security;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: CLSCompliantAttribute(true)]
[assembly: AssemblyTitleAttribute("NHibernate.Validator")]
[assembly: AssemblyDescriptionAttribute("NHibernate Validator")]
[assembly: AssemblyCompanyAttribute("nhforge.org")]
[assembly: AssemblyProductAttribute("NHibernate.Validator")]
[assembly: AssemblyCopyrightAttribute("Licensed under LGPL.")]
[assembly: AssemblyVersionAttribute("1.0.0.4000")]
[assembly: AssemblyInformationalVersionAttribute("1.0.0.4000")]
[assembly: AssemblyFileVersionAttribute("1.0.0.4000")]
[assembly: AssemblyDelaySignAttribute(false)]
[assembly: AllowPartiallyTrustedCallersAttribute()]

