using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Security;

//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.3053
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: CLSCompliantAttribute(true)]
[assembly: AssemblyTitleAttribute("NHibernate.Validator.Specific")]
[assembly: AssemblyDescriptionAttribute("NHibernate Validator: Validators country specific.")]
[assembly: AssemblyCompanyAttribute("NHibernate Community - www.nhforge.org")]
[assembly: AssemblyProductAttribute("NHibernate.Validator.Specific")]
[assembly: AssemblyCopyrightAttribute("Licensed under LGPL.")]
[assembly: AssemblyVersionAttribute("1.2.0.1001")]
[assembly: AssemblyInformationalVersionAttribute("1.2.0.1001")]
[assembly: AssemblyFileVersionAttribute("1.2.0.1001")]
[assembly: AssemblyDelaySignAttribute(false)]
[assembly: AssemblyKeyFileAttribute("..\\..\\..\\..\\src\\NHibernate.Validator.snk")]
[assembly: AllowPartiallyTrustedCallersAttribute()]

