using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Security;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: CLSCompliantAttribute(true)]
[assembly: AssemblyTitleAttribute("NHibernate.Validator.Specific")]
[assembly: AssemblyDescriptionAttribute("NHibernate Validator: Validators country specific.")]
[assembly: AssemblyCompanyAttribute("NHibernate Community - www.nhforge.org")]
[assembly: AssemblyProductAttribute("NHibernate.Validator.Specific")]
[assembly: AssemblyCopyrightAttribute("Licensed under LGPL.")]
[assembly: AssemblyVersionAttribute("1.2.0.1003")]
[assembly: AssemblyInformationalVersionAttribute("1.2.0.1003")]
[assembly: AssemblyFileVersionAttribute("1.2.0.1003")]
[assembly: AssemblyDelaySignAttribute(false)]
[assembly: AssemblyKeyFileAttribute("..\\..\\..\\..\\src\\NHibernate.Validator.snk")]
[assembly: AllowPartiallyTrustedCallersAttribute()]

